### ISSUE TITLE
v1.4.0 has a binary name issue

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/browser-tools-orb#54] opened 2022-07-21 17:04 UTC
Waiting for customer feedback here but my initial tests suggest this might only be affecting macOS?

**Comment by aharpervc** [comment] 2022-07-21 18:17
> @aharpervc Hey. What params are you using? Can you add that info to https://github.com/CircleCI-Public/browser-tools-orb/issues/54 please?

> 
> Basically, what OS, desired channel, and are you using stable or specifying a version? We can get this fixed promptly.

My orb configuration in circleci/.config.yml is:

```
  browser-tools: circleci/browser-tools@1
```

and I'm setting it up in my workflow with this job step:

```
    steps:
      - browser-tools/install-browser-tools
```

Otherwise, I'm not explicitly specifying anything

I'm using a custom docker image as the base environment image, based on ubuntu. The tests are for a Rails app using Selenium & Capybara.

Formerly, this orb installed `/usr/bin/google-chrome`, and everything worked fine. With the recent change to enable Chrome beta, it looks like the binary is now called `/usr/bin/google-chrome-stable`. This is a surprising change, and it causes this error when my app tests run:

```
Selenium::WebDriver::Error::UnknownError:
  unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

**Comment by felicianotech** [comment] 2022-07-21 18:41
Thanks for the info. My current test on Linux shows that `/usr/bin/google-chrome` exists so I'm trying to figure out what's happening. Stay tuned. As you might have already figured out, you can lock the orb to `1.3` or `1.3.0` in order to avoid this issue for now.

**Comment by aharpervc** [comment] 2022-07-21 19:31
> As you might have already figured out, you can lock the orb to `1.3` or `1.3.0` in order to avoid this issue for now.

Thanks, this will unblock me for the moment

> ?

SSHing into a worker instance I see that both `/usr/bin/google-chrome` and `/usr/bin/google-chrome-stable` are symlinks... I'm expecting that `google-chrome-stable` was installed by this orb. Not sure about `google-chrome`. Maybe it was previously overwritten by browser-tools, and now is generally present?

```
lrwxrwxrwx 1 root root      31 Jul 21 19:23 /usr/bin/google-chrome -> /etc/alternatives/google-chrome
lrwxrwxrwx 1 root root      32 Jul 18 19:14 /usr/bin/google-chrome-stable -> /opt/google/chrome/google-chrome
```

**Comment by BytesGuy** [comment] 2023-05-24 07:34
Hi, I have tried to reproduce this issue but have been unable to do so. Both symlinks point to the same version of Chrome which is installed by the browser tools orb. It is possible that this issue is stemming from the custom image which you are using, even though it is Ubuntu based. As I have not been able to reproduce the issue, and there have been no further reports about this problem, I will close this issue for now. If you have any more information we can use for debugging, please let us know. Thanks!

**Closed by BytesGuy** 2023-05-24 07:34 UTC
