### ISSUE TITLE
Browser Tools v2

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/browser-tools-orb#40] opened 2022-03-29 10:59 UTC
Considerations for v2 of the orb:

- Chrome
  - On Debian and Ubuntu based systems, switching to the Debian repository. This should allow us to go back as many versions as we go now, or at least close to it. The main reason for this is to avoid the curl download issue we're experiencing now with the orb.
  - Installing Beta and Canary versions of the Chrome
- Orb Tools 11

**Comment by KyleTryon** [comment] 2022-04-14 14:39
* Chrome
  * #48 contains this feature update
  * Duplicate of #23 
* Merged in #46

**Closed** 2022-04-26 18:58 UTC
