### ISSUE TITLE
Installing Chrome fails (exit status 18)

### ISSUE THREAD

**Issue by bhb** [CircleCI-Public/browser-tools-orb#33] opened 2021-08-31 21:26 UTC
### Orb version

version 1.2.1

### What happened

`browser-tools/install-chrome` (with no chrome version set, so it should be "latest")

fails with

```
Google Chrome is not currently installed; installing it
curl: (18) transfer closed with 72364364 bytes remaining to read

Exited with code exit status 18
CircleCI received exit code 18
```

e.g. https://app.circleci.com/pipelines/github/wunderteam/portal/10969/workflows/233c3e6e-65df-474d-bf2f-d2f2c07a932e/jobs/90380

This happens in roughly 75% of our builds

### Expected behavior

`browser-tools/install-chrome` should complete without error

### Workaround

I updated our config to hardcode the Chrome version, which fixed the issue:

```
  - browser-tools/install-chrome:
      chrome-version: "92.0.4515.159"
```

This seems to suggest the issue is with downloading the latest version of Chrome from https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

**Comment by jacobgavin** [comment] 2021-09-01 08:45
We got the same issue. I tried your workaround but that doesn't work either. 
I've tried all the URLs for the different chrome downloads and they all work locally, i.e. https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_92.0.4515.159-1_amd64.deb works locally in browser.

**Comment by gmemstr** [comment] 2021-09-01 11:46
Dupe of https://github.com/CircleCI-Public/browser-tools-orb/issues/34 (I suspect) so closing this issue in favour of that thread.

**Comment by bhb** [comment] 2021-09-01 18:03
@gmemstr Despite #34 being resolved, we're still seeing this issue on our builds

https://app.circleci.com/pipelines/github/wunderteam/portal/11046/workflows/3dd1f2c0-cd4f-4521-beb9-750d610a4c8c/jobs/90730

**Comment by bhb** [comment] 2021-09-03 15:15
Update: I tried again today and it seems fine now, so this may be resolved?

**Comment by bhb** [comment] 2022-02-24 02:09
I've seen this error 3 times in the last few hours.

**Comment by bhb** [comment] 2022-03-15 15:46
We continue to see this failure regularly.

**Comment by bhb** [comment] 2022-03-21 18:27
We've seen this fail more than ten times across many different jobs, and it's currently blocking our ability to deploy (since we use CircleCI for continuous deployment).

Is it possible to set a higher number of retries, or add a setting to cache the downloads for some period of time?

**Comment by tetienne** [comment] 2022-03-22 13:50
I can confirm, we face this issue a lot since yesterday.

**Comment by danrice92** [comment] 2022-03-22 15:28
I had this issue too.

Workaround for now was to specify the Chrome version:

```
- browser-tools/install-chrome:
    chrome-version: 85.0.4183.102
```

**Comment by kreintjes** [comment] 2022-03-23 12:37
Same issue over here. Strangely enough for now we only see it fail in one of our projects, but not in another project which uses the same browser-tools version (but maybe it will start failing there soon as well).

I will try the specific Chrome version work around (thanks everybody), but a proper fix in this orb for installing the latest Chrome version would be great!
Btw is this a community project or developed/maintained by the CircleCI team?

**Comment by ramonpm** [comment] 2022-03-24 22:13
Also seeing this issue very often.

**Comment by jkzilla** [comment] 2022-03-28 18:06
👋 the below provides the fallback to continue the download using http1.1 if the initial curl doesn’t succeed:

```
curl --silent --show-error --location --fail --retry 3 --output google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /dev/null 2>&1; then

curl --http1.1 -L -o google-chrome.deb -C - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

fi
```

**Closed** 2022-03-29 13:56 UTC

**Comment by joerodrig** [comment] 2022-04-05 03:48
I was having this problem earlier on a workflow that ran many parallel jobs that ended up downloading Chrome in each one. I ended up extending the base node-browsers image CircleCI provides with the Chrome download that was [included in the legacy base images](https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.5.3-stretch/node-browsers/Dockerfile#L50-L64), so my custom image looked like this:
```shell
FROM cimg/node:<NODE_VERSION>-browsers


RUN curl --silent --show-error --location --fail --retry 3 --output /tmp/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && (sudo dpkg -i /tmp/google-chrome-stable_current_amd64.deb || sudo apt-get -fy install)  \
  && rm -rf /tmp/google-chrome-stable_current_amd64.deb \
  && sudo sed -i 's|HERE/chrome"|HERE/chrome" --disable-setuid-sandbox --no-sandbox|g' \
  "/opt/google/chrome/google-chrome" \
  && google-chrome --version

RUN export CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE) \
  && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
  && cd /tmp \
  && unzip chromedriver_linux64.zip \
  && rm -rf chromedriver_linux64.zip \
  && sudo mv chromedriver /usr/local/bin/chromedriver \
  && sudo chmod +x /usr/local/bin/chromedriver \
  && chromedriver --version
```

This seems to have resolved the issue since now Chrome is only downloaded when a new image is created, which is happening outside of CI.
