### ISSUE TITLE
Cannot find 1.4.4 in orb registry

### ISSUE THREAD

**Issue by MarcinVaadin** [CircleCI-Public/browser-tools-orb#89] opened 2023-08-02 18:29 UTC
### Orb version

1.4.4

### What happened

```
Cannot find circleci/browser-tools@1.4.4 in the orb registry. Check that the namespace, orb name and version are correct.
```

### Expected behavior

According to https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.4 I would expect it available :-)

**Comment by benmvp** [comment] 2023-08-17 22:41
We're seeing a problem where the latest ChromeDriver somehow is incompatible with the latest Chrome version. This seems to have been fixed with #85 that was supposedly released with 1.4.4, but it's [not in the registry](https://circleci.com/developer/orbs/orb/circleci/browser-tools?version=1.4.4):

**Comment by returnv01d** [comment] 2023-08-23 08:23
hello @ryanbourdais, can we please add new version to registry?

**Comment by ryanbourdais** [comment] 2023-08-24 20:25
Hi all, it seems that the build failed when I cut the release and as a result it was not published. Sorry I did not catch this sooner, I have rerun the build and the orb version should now be published.

**Closed by ryanbourdais** 2023-08-24 20:25 UTC

**Comment by benmvp** [comment] 2023-08-29 20:40
Thanks for the fix @ryanbourdais! I now see [1.4.4](https://circleci.com/developer/orbs/orb/circleci/browser-tools?version=1.4.4) in the registry. but when I use it, I'm getting the following error. 

```
Installed version of Google Chrome is 116.0.5845.140 
ChromeDriver 116.0.5845.140 will be installed
116.0.5845.140 will be installed
curl: (22) The requested URL returned error: 404

Exited with code exit status 22
```

Unfortunately, I don't know what URL is being curl'd to be able to debug further.

**Comment by ryanbourdais** [comment] 2023-08-29 20:49
Hi @benmvp it seems that google released a new version of chrome without a coinciding version of chrome driver, the orb is working as inteded but for now you will need to specify a chrome version [here is the current releases](https://googlechromelabs.github.io/chrome-for-testing/).

**Comment by benmvp** [comment] 2023-08-29 20:51
Thanks for that link! One more thing I can look at in the future for debugging

**Comment by benmvp** [comment] 2023-08-29 20:55
@ryanbourdais would it make sense to find the latest chrome driver and then load the equivalent browser version? Not sure how the code works...

**Comment by ryanbourdais** [comment] 2023-08-29 20:58
@benmvp the current way the orb works detects the active chrome version and downloads the chrome driver version that matches it

**Comment by ryanbourdais** [comment] 2023-08-29 21:30
@benmvp I think the issue is that chrome [released a new chrome version](https://chromereleases.googleblog.com/) today as stable, thats why the chrome for testing site shows it as upcoming, since they did not release a chrome driver version alongside it. This issue should be resolved soon though by google
