### ISSUE TITLE
`install-chromedriver` is broken for Chrome >= 115 which is stable and latest release today

### ISSUE THREAD

**Issue by bericp1** [CircleCI-Public/browser-tools-orb#75] opened 2023-07-18 19:44 UTC
### Orb version

circleci/browser-tools@1.4.1 (latest as of writing)

### What happened

`chromedriver` install fails:

![](https://d.pr/i/zoQmLE.png)

This is because the `chromedriver` team migrated to a new set of JSON APIs for >=115

https://sites.google.com/chromium.org/driver/?pli=1#:~:text=Starting%20with%20M115%20the%20latest%20Chrome%20%2B%20ChromeDriver%20releases%20per%20release%20channel%20(Stable%2C%20Beta%2C%20Dev%2C%20Canary)%20are%20available%20at%20the%20Chrome%20for%20Testing%20availability%20dashboard.%20For%20automated%20version%20downloading%20one%20can%20use%20the%20convenient%20JSON%20endpoints.

### Expected behavior

ChromeDriver installs

**Comment by josephfrazier** [comment] 2023-07-18 20:03
I'm experiencing this as well, also on browser-tools version 1.4.1

**Comment by Jaym3s** [comment] 2023-07-18 20:05
Here's a workaround for others that are hitting this:
```
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 114.0.5735.90 # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
```

**Comment by jonathandean** [comment] 2023-07-18 20:43
I had already tried what @Jaym3s mentioned but got this:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 google-chrome-stable : Depends: fonts-liberation but it is not installable
                        Depends: libatk-bridge2.0-0 (>= 2.5.3) but it is not installable
                        Depends: libatk1.0-0 (>= 2.2.0) but it is not installable
                        Depends: libatspi2.0-0 (>= 2.9.90) but it is not installable
                        Depends: libcups2 (>= 1.6.0) but it is not installable
                        Depends: libgtk-3-0 (>= 3.9.10) but it is not installable or
                                 libgtk-4-1 but it is not installable
                        Depends: libnspr4 (>= 2:4.9-2~) but it is not installable
                        Depends: libnss3 (>= 2:3.31) but it is not installable
                        Depends: libu2f-udev but it is not installable
                        Depends: libvulkan1 but it is not installable
                        Depends: libxcomposite1 (>= 1:0.4.4-1) but it is not installable
                        Depends: libxdamage1 (>= 1:1.1) but it is not installable
                        Depends: xdg-utils (>= 1.0.2) but it is not installable
```

**Comment by josephfrazier** [comment] 2023-07-18 20:59
I [created a CircleCI support request](https://support.circleci.com/hc/en-us/requests/new?ticket_form_id=855268) pointing them to this github issue, to try to get it escalated.

**Comment by jonathandean** [comment] 2023-07-18 21:08
If anyone is curious this is the announcement of the breaking change in May: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE/m/5NxzS_SRAgAJ

**Comment by jonathandean** [comment] 2023-07-18 21:13
Looks like this PR is related as it mentions this general problem: https://github.com/CircleCI-Public/browser-tools-orb/pull/72

**Comment by josephfrazier** [comment] 2023-07-18 21:15
> If anyone is curious this is the announcement of the breaking change in May: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE/m/5NxzS_SRAgAJ

Thanks, it looks like that should help CircleCI fix this faster

**Comment by goodish452** [comment] 2023-07-18 21:16
Workaround works well enough for our purposes. But it will definitely impact a lot of our overnight runs until teams can go through and add the workaround.

**Comment by olihensel** [comment] 2023-07-18 21:20
I had the same problem as @jonathandean with the workaround. Running `sudo apt-get update` in a step before installing the browser fixed it for me.

**Comment by gaijin1973** [comment] 2023-07-18 21:22
@olihensel, thanks for the suggestion. I was just looking at the PR that @jonathandean posted, and it looks like this line may be the one that was intended to address the issues without your workaround:
https://github.com/CircleCI-Public/browser-tools-orb/pull/72/files#diff-5432426082806dd0f398e088bb8e20badcd780a34783e189aad77f9241ace0edR127

**Comment by ryanbourdais** [comment] 2023-07-18 21:34
Hi all, I'm currently working on a fix and should have one out today. This issue was caused by the endpoint we use for downloading chrome driver changing for all versions >= 115.

**Comment by gaijin1973** [comment] 2023-07-18 21:40
> I had the same problem as @jonathandean with the workaround. Running `sudo apt-get update` in a step before installing the browser fixed it for me.

Just to reiterate / summarize the update from @olihensel to the original workaround posted by @Jaym3s, this seems to have gotten me past the browser-tools step in our workflow:
```
steps:
  - run: sudo apt-get update
  - browser-tools/install-chrome:
      chrome-version: "114.0.5735.90"
```

**Comment by ryanbourdais** [comment] 2023-07-18 23:53
Just merged in the PR and cut a [new patch release](https://github.com/CircleCI-Public/browser-tools-orb/releases/tag/v1.4.2). Chrome driver should work for versions newer than 114 on this new version of the orb.

**Closed by ryanbourdais** 2023-07-18 23:53 UTC

**Comment by eveshum** [comment] 2023-07-19 00:31
I'm getting this error when bumping to 1.4.2

```#!/bin/bash -eo pipefail
google-chrome --version
chromedriver --version

Google Chrome 115.0.5790.98 
/bin/bash: line 1: chromedriver: command not found

Exited with code exit status 127
CircleCI received exit code 127```

Did anyone else get this?

**Comment by josephfrazier** [comment] 2023-07-19 00:36
My builds are installing version 108, not 115....

```
Installed version of Google Chrome is 108.0.5359.124 
ChromeDriver 108.0.5359.71 will be installed
^@^@ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) has been installed to /usr/local/bin/chromedriver
```

**Comment by kelvintaywl** [comment] 2023-07-19 01:27
> I'm getting this error when bumping to 1.4.2
> 
> ```
> google-chrome --version
> chromedriver --version
> 
> Google Chrome 115.0.5790.98 
> /bin/bash: line 1: chromedriver: command not found
> 
> Exited with code exit status 127
> CircleCI received exit code 127
> ```
> 
> Did anyone else get this?

Hi @eveshum

This is Kelvin from CircleCI support.

Thank you for raising this.
I understand you have filed a support ticket with us at CircleCI as well.

For a workaround and an explanation of the issue seen, can you try updating your job as seen with this PR's diff:
https://github.com/kelvintaywl-cci/browser-tools-142/pull/1/files

I am sharing this with our engineers in the meantime;
Thank you for your patience! 🙇

**Comment by MikeMcElroy** [comment] 2023-07-19 01:38
> Hi @eveshum
> 
> This is Kelvin from CircleCI support.
> 
> Thank you for raising this. I understand you have filed a support ticket with us at CircleCI as well.
> 
> For a workaround and an explanation of the issue seen, can you try updating your job as seen with this PR's diff: https://github.com/kelvintaywl-cci/browser-tools-142/pull/1/files
> 
> I am sharing this with our engineers in the meantime; Thank you for your patience! 🙇

@kelvintaywl That seems to work for me :+1:

**Comment by snyaggarwal** [comment] 2023-07-19 05:03
> > I had the same problem as @jonathandean with the workaround. Running `sudo apt-get update` in a step before installing the browser fixed it for me.
> 
> Just to reiterate / summarize the update from @olihensel to the original workaround posted by @Jaym3s, this seems to have gotten me past the browser-tools step in our workflow:
> 
> ```
> steps:
>   - run: sudo apt-get update
>   - browser-tools/install-chrome:
>       chrome-version: "114.0.5735.90"
> ```

This worked for ubuntu builds but not for macos. From the documentation, "chrome-version" doesnt work in MacOS. Any workaround for macOS builds?

**Comment by snyaggarwal** [comment] 2023-07-19 05:18
> > I'm getting this error when bumping to 1.4.2
> > ```
> > google-chrome --version
> > chromedriver --version
> > 
> > Google Chrome 115.0.5790.98 
> > /bin/bash: line 1: chromedriver: command not found
> > 
> > Exited with code exit status 127
> > CircleCI received exit code 127
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did anyone else get this?
> 
> Hi @eveshum
> 
> This is Kelvin from CircleCI support.
> 
> Thank you for raising this. I understand you have filed a support ticket with us at CircleCI as well.
> 
> For a workaround and an explanation of the issue seen, can you try updating your job as seen with this PR's diff: https://github.com/kelvintaywl-cci/browser-tools-142/pull/1/files
> 
> I am sharing this with our engineers in the meantime; Thank you for your patience! 🙇

@kelvintaywl On MacOS this installs the chrome and driver but in verify step fails with:
/bin/bash: google-chrome: command not found

**Comment by snyaggarwal** [comment] 2023-07-19 06:39
for others using MacOS and facing the same issue, this is the way we fixed it using `circleci/browser-tools@1.4.2`
```
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Fix PATH
          command: |
            ln -s /usr/local/bin/google-chrome-stable /usr/local/bin/google-chrome
            mv /usr/local/bin/chromedriver /usr/local/bin/chromedriver2
            ln -s /usr/local/bin/chromedriver2/chromedriver /usr/local/bin/chromedriver
            echo 'export PATH=/usr/local/bin/google-chrome:$PATH' >> $BASH_ENV
            echo 'export PATH=/usr/local/bin/chromedriver:$PATH' >> $BASH_ENV
```

Due to following differences on MacOS:
- chromedriver is installed in `/usr/local/bin/chromedriver/chromedriver`
- google chrome is installed as /usr/local/bin/google-chrome-stable

**Comment by jonathandean** [comment] 2023-07-19 13:33
> > I had the same problem as @jonathandean with the workaround. Running `sudo apt-get update` in a step before installing the browser fixed it for me.
> 
> Just to reiterate / summarize the update from @olihensel to the original workaround posted by @Jaym3s, this seems to have gotten me past the browser-tools step in our workflow:
> 
> ```
> steps:
>   - run: sudo apt-get update
>   - browser-tools/install-chrome:
>       chrome-version: "114.0.5735.90"
> ```

Thanks to all of you! The above workaround worked and I'll obviously try 1.4.2 next. It's nice to have green builds again :)

**Comment by jonathandean** [comment] 2023-07-19 13:45
Also can confirm that `circleci/browser-tools@1.4.2` worked for me on ubuntu with no need to pin a chrome version or run `apt-get update`.

**Comment by jonathandean** [comment] 2023-07-19 13:59
> Also can confirm that `circleci/browser-tools@1.4.2` worked for me on ubuntu with no need to pin a chrome version or run `apt-get update`.

Actually I spoke too soon. The install part worked but something about the install path or other things about my setup are not quite right:

```
Selenium::WebDriver::Error::WebDriverError:
  chromedriver located, but: not a file: "/usr/local/bin/chromedriver"
```

**Comment by JasonBarnabe** [comment] 2023-07-19 14:04
With 1.4.2 I get past the chromedriver install but I fail in my Rails app tests:

```
Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
```

Keeping the setting `chrome-version: "114.0.5735.90"` per previous comments, it works.

**Comment by albertski** [comment] 2023-07-19 14:23
I confirm that upgrading to `1.4.2` and adding the run to match https://github.com/kelvintaywl-cci/browser-tools-142/pull/1/files fixes the issue:
```
      - run:
          name: Fix PATH
          command: |
            echo "see https://github.com/CircleCI-Public/browser-tools-orb/blob/de5fa4e28909039438189815dbb42ac308e49bc9/src/scripts/install-chromedriver.sh#L187"
            echo "export PATH='/usr/local/bin/chromedriver:$PATH'" >> $BASH_ENV
```

**Comment by albertski** [comment] 2023-07-19 15:33
I confirm that upgrading to `1.4.2` and adding the `run` to match https://github.com/kelvintaywl-cci/browser-tools-142/pull/1/files doesn't cause the ChromeDriver Error now:
```
      - run:
          name: Fix PATH
          command: |
            echo "see https://github.com/CircleCI-Public/browser-tools-orb/blob/de5fa4e28909039438189815dbb42ac308e49bc9/src/scripts/install-chromedriver.sh#L187"
            echo "export PATH='/usr/local/bin/chromedriver:$PATH'" >> $BASH_ENV
```


But now getting the following errors in my specs:

```
  Webdrivers::VersionError:
    Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known
```

**Comment by ryanbourdais** [comment] 2023-07-19 19:06
Orb version 1.4.3 was just released which should work without the workaround from @kelvintaywl

**Comment by JasonBarnabe** [comment] 2023-07-19 19:50
1.4.3 still fails in my tests unless I have `chrome-version: "114.0.5735.90"`:

```
Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
```

**Comment by MikeMcElroy** [comment] 2023-07-19 19:53
For my part, 1.4.3 worked for me after I removed all the workarounds. :+1:

**Comment by ryanbourdais** [comment] 2023-07-19 19:56
> 1.4.3 still fails in my tests unless I have `chrome-version: "114.0.5735.90"`:
> 
> ```
> Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome. Please set `Webdrivers::Chromedriver.required_version = <desired driver version>` to a known chromedriver version: https://chromedriver.storage.googleapis.com/index.html
> ```

@JasonBarnabe it seems that you're missing the last part of the version string as stable is 115.0.5790.98 but it seems you only passed 115.0.5790.98. What image are you using, and can you give an example config?

**Comment by JasonBarnabe** [comment] 2023-07-19 20:03
https://app.circleci.com/pipelines/github/Simplero/Simplero/53516/workflows/c2f2c374-4096-4676-9d68-35d15ebb6074/jobs/63338/tests shows the failure - I imagine you can view the config with that info?

**Comment by ryanbourdais** [comment] 2023-07-19 20:14
Hi @JasonBarnabe it seems that your tests are checking valid chromedriver versions using [the old api](https://app.circleci.com/pipelines/github/Simplero/Simplero/53516/workflows/c2f2c374-4096-4676-9d68-35d15ebb6074/jobs/63338/steps?invite=true#step-117-699_151). If you click the [link](https://chromedriver.storage.googleapis.com/index.html) in the error message it sends you to the old api endpoint. It seems to me that the orb is now working as intended in your builds and that [submitting a support request](https://support.circleci.com/hc/en-us/requests/new) is the best way to continue.

**Comment by JasonBarnabe** [comment] 2023-07-19 20:17
I believe that the issue I reported is [with the webdrivers gem](https://github.com/titusfortner/webdrivers/issues/247) - caused by the same underlying change to the ChromeDriver release process, but not specifically related to Circle. As mentioned previously, adding `chrome-version: "114.0.5735.90"` fixes it.

**Comment by albertski** [comment] 2023-07-20 18:15
After updating to 1.4.3, I'm still having the following errors during my system spec runs (no issues with the [workaround](https://github.com/CircleCI-Public/browser-tools-orb/issues/75#issuecomment-1641031119)):

```
  # --- Caused by: ---
  # Webdrivers::NetworkError:
  #   Net::HTTPServerException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
  #   /home/circleci/project/vendor/bundle/ruby/3.0.0/gems/webdrivers-5.2.0/lib/webdrivers/network.rb:19:in `get'
```

**config.yml**
```
  browser-tools: circleci/browser-tools@1.4.3
...
...
  
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
```

**Comment by bechin92** [comment] 2023-07-21 07:38
I'm sorry. I have a question.
Please tel me when will chrome 115 be released on https://chromedriver.chromium.org/downloads

**Comment by MikeMcC399** [comment] 2023-07-21 07:52
@bechin92 

> I'm sorry. I have a question. Please tel me when will chrome 115 be released on https://chromedriver.chromium.org/downloads

https://chromedriver.chromium.org/downloads links to https://googlechromelabs.github.io/chrome-for-testing/ where `115` is listed under the [Stable](https://googlechromelabs.github.io/chrome-for-testing/#stable) Channel. In other words it has already been released.

**Comment by neliojrr** [comment] 2023-07-25 15:03
Updating to 1.4.3 worked for me. Thanks!!

**Comment by snyaggarwal** [comment] 2023-07-26 03:19
on MacOS it has started throwing 404 while installing chromedriver 115.0.5790.114, using 1.4.3. Any help?

**Comment by marco-emmanuel-noto** [comment] 2023-08-10 07:12
Updating to 1.4.3 worked for me too!

**Comment by mightystrong** [comment] 2023-08-29 19:31
> Here's a workaround for others that are hitting this:
> 
> ```
>     steps:
>       - browser-tools/install-browser-tools:
>           chrome-version: 114.0.5735.90 # TODO: remove -> https://github.com/CircleCI-Public/browser-tools-orb/issues/75
> ```

I was using 1.4.3 with no issues until today. But then the issue sprang up on me. I then upgraded to 1.4.4 with no success. Turns out, I still needed to specify the chrome stable version because browser tools was trying to install an unreleased version of chrome/chromdriver. It's trying to install version 116.0.5845.140, but the corresponding chromedriver doesn't exist and so the pipeline failed.

![Screenshot 2023-08-29 at 1 25 04 PM](https://github.com/CircleCI-Public/browser-tools-orb/assets/5291904/9067a447-2440-4827-a81d-e4016c946522)

Changing the step to the following worked for me, but I think a more permanent solution would be great. It was unclear without a lot of digging how to fix this. Thanks for all your work on this project.

```
- browser-tools/install-chrome:
     chrome-version: 116.0.5845.96
```

**Comment by mantrala** [comment] 2023-08-29 19:50
@mightystrong I tried the latest `1.4.4` with the chrome version specified to `116.0.5845.96` and getting an error `/bin/bash: line 130: google-chrome-stable: command not found`

**Comment by 0xadada** [comment] 2023-08-29 20:13
this worked for me
```
- run: sudo apt-get update
- browser-tools/install-chrome:
    # TODO remove following line when fixed https://github.com/CircleCI-Public/browser-tools-orb/issues/90
    chrome-version: 116.0.5845.96
```

**Comment by mightystrong** [comment] 2023-08-29 20:34
> 

@mantrala Not sure what to recommend without seeing the rest of the config.

**Comment by hawkrush** [comment] 2023-08-29 20:49
Thanks @0xadada, that worked for me!

**Comment by HennaAbbas** [comment] 2023-08-29 20:54
Hi All, 

We recommend specifying a chromedriver-version. This should resolve the issue. The root cause of this issue is the latest release of chromedriver : https://chromereleases.googleblog.com/

**Comment by mantrala** [comment] 2023-08-29 21:36
@hoylemd @0xadada need `sudo apt-get update` to get the build going. Thank you.

**Comment by sedghi** [comment] 2023-12-13 15:16
I have this issue in my circleCI

**Comment by albertski** [comment] 2023-12-13 15:21
@sedghi What version of `browser-tools-orb` are you using? Perhaps you need to update to the latest (`v1.4.6`).

**Comment by sedghi** [comment] 2023-12-13 22:16
I think i'm on latest? https://github.com/OHIF/Viewers/blob/master/.circleci/config.yml
I don't specify it really

**Comment by artemgurzhii** [comment] 2024-05-16 08:37
```
Google Chrome is not currently installed; installing it
Preparing Chrome installation for Debian-based systems
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb:
2024-05-16 08:04:25 ERROR 404: Not Found.
/bin/bash: line 130: google-chrome-stable: command not found
Google Chrome v114.0.5735.90 (stable) failed to install.

Exited with code exit status 1
```

**Comment by craigd-lumin** [comment] 2024-05-16 09:08
Same for me.
`Google Chrome is not currently installed; installing it
Preparing Chrome installation for Debian-based systems
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb:
2024-05-16 09:02:39 ERROR 404: Not Found.
/bin/bash: line 130: google-chrome-stable: command not found
Google Chrome v114.0.5735.90 (stable) failed to install.`

**Comment by jmetric** [comment] 2024-05-16 14:02
> ```
> Google Chrome is not currently installed; installing it
> Preparing Chrome installation for Debian-based systems
> https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb:
> 2024-05-16 08:04:25 ERROR 404: Not Found.
> /bin/bash: line 130: google-chrome-stable: command not found
> Google Chrome v114.0.5735.90 (stable) failed to install.
> 
> Exited with code exit status 1
> ```

This solution may not work if you are using MacOS, but we upgraded our browser tools to 1.4.2 (`browser-tools: circleci/browser-tools@1.4.2`) and removed the explicit browser-tools/install-browser-tools: #chrome-version: 114.0.5735.90 lines and this resolved the issue for us.

Google appears to have made several changes to Chrome versions yesterday (https://chromereleases.googleblog.com/2024/) though I was unable to find a reference to version 114.

**Comment by adamdupuis** [comment] 2024-05-16 14:09
@artemgurzhii @craigd-lumin

Make sure you are using a more recent version of `browser-tools`. I'm using `circleci/browser-tools@1.4.8`. I had to begin using Chrome v116.0.5845.96 or greater:

```
- browser-tools/install-chrome:
    chrome-version: "116.0.5845.96"
```

The problem is these old versions are removed from Google's mirrors. This version will likely be removed in the next month or so.

**Comment by mightystrong** [comment] 2024-05-16 14:09
> Same for me. `Google Chrome is not currently installed; installing it Preparing Chrome installation for Debian-based systems https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb: 2024-05-16 09:02:39 ERROR 404: Not Found. /bin/bash: line 130: google-chrome-stable: command not found Google Chrome v114.0.5735.90 (stable) failed to install.`

We experienced this issue frequently. The following implementation has been stable. Specific chrome versions are unstable as Google doesn't consistently maintain availability.

```
orbs:
  browser-tools: circleci/browser-tools@1.4.6
.
.
.
    steps:
      - attach_workspace:
          at: /your/workspace
      - browser-tools/install-chrome
      - run:
          command: |
            google-chrome --version
          name: Check install
      - checkout
.
.
.
```

**Comment by artemgurzhii** [comment] 2024-05-16 14:21
@adamdupuis thank you for help! we were having `browser-tools: circleci/browser-tools@1.4.2` and `chrome-version: 114.0.5735.90`, replaced with `browser-tools: circleci/browser-tools@1.4.8` and `chrome-version: 116.0.5845.96`, works fine now!

**Comment by craigd-lumin** [comment] 2024-05-16 15:22
Thanks for the help @adamdupuis , much appreciated!

**Comment by thiagosf** [comment] 2024-05-17 19:20
Thanks, @adamdupuis! If anyone stumbles into this error:

```
Webdrivers::NetworkError:
       Net::HTTPClientException: 404 "Not Found" with https://chromedriver.storage.googleapis.com/116.0.5845.96/chromedriver_linux64.zip
```

It is fixed by updating the `selenium-webdriver` to `4.16.0`.

**Comment by levischuckeats** [comment] 2024-06-03 20:59
Our team ran into this and no matter what version we tried, no chrome version listed on [chrome driver downloads](https://developer.chrome.com/docs/chromedriver/downloads) would resolve.
The solution I came up with was to swap out the install section with the following script for debian environments:
```yaml
      - run: |
          echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee -a /etc/apt/sources.list.d/chrome.list
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
```
